### ISSUE TITLE
Xin Workflow và Slide của buổi present

### ISSUE THREAD

**Issue by lphnam** [vietdien2005/workshop-prometheus#1]
Hi anh Việt, 
Trong buổi present, em thấy anh có share Workflow. Anh có thể đính kèm vào repo luôn được không ạ?

Cảm ơn anh về buổi present.

**Comment by vietdien2005** [comment]
Mình cập nhật trong Readme, có đính kèm cả file `workshop.pptx` rồi nhé :smile: 

Cảm ơn bạn đã quan tâm
